line-length = 127
indent-width = 4

[lint]
extend-select = ["A", "B", "D", "E501", "F", "I", "UP"]
ignore = ["D100", "D101", "D103", "D104", "D107", "D203", "D213"]

[format]
indent-style = "space"
line-ending = "lf"
quote-style = "single"
